### ISSUE TITLE
Web3j does not exit after subscription.unsubscribe()

### ISSUE THREAD

**Issue by frasierw** [web3j/web3j#206] opened 2017-10-26 08:43 UTC
Hello, I'm using web3j 2.3.1 release. It seems that subscription.unsubscribe() doesn't actually stop web3j client, is this expected?

        Web3j web3 = Web3j.build(new HttpService());
        Subscription subscription = web3.blockObservable(true).subscribe(block -> {
            System.out.println("Sweet, block number " + block.getBlock().getNumber() + " has just been created");
        }, Throwable::printStackTrace);
        TimeUnit.SECONDS.sleep(10);
        subscription.unsubscribe();

**Comment by conor10** [comment] 2017-11-13 08:59
Testing using web3j 3.1.0:

```java
   @Test
    public void test() throws Exception {
        Web3j web3 = Web3j.build(new HttpService());
        Subscription subscription = web3.blockObservable(true).subscribe(block -> {
            System.out.println("Sweet, block number " + block.getBlock().getNumber() + " has just been created");
        }, Throwable::printStackTrace);
        TimeUnit.SECONDS.sleep(10);
        subscription.unsubscribe();

        System.out.println("here");
        TimeUnit.MINUTES.sleep(1);
    }
```

Console output is below - you can see the following unsubscribe call:

```javascript
{"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x843a487b90055781bab0fba99489889e"],"id":2}
```

In the logs below:

```bash
08:56:33.412 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
08:56:33.418 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
08:56:33.418 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 66
08:56:33.419 [main] DEBUG org.web3j.protocol.http.HttpService - 
08:56:33.420 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":0}
08:56:33.420 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (66-byte body)
08:56:33.490 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (69ms)
08:56:33.490 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
08:56:33.490 [main] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 13 Nov 2017 08:56:33 GMT
08:56:33.490 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 71
08:56:33.491 [main] DEBUG org.web3j.protocol.http.HttpService - 
08:56:33.492 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":0,"result":"0x843a487b90055781bab0fba99489889e"}

08:56:33.492 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (71-byte body)
08:56:33.728 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
08:56:33.728 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
08:56:33.728 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 104
08:56:33.728 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
08:56:33.728 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x843a487b90055781bab0fba99489889e"],"id":1}
08:56:33.728 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> END POST (104-byte body)
08:56:33.731 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (2ms)
08:56:33.731 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
08:56:33.734 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 13 Nov 2017 08:56:33 GMT
08:56:33.734 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 37
08:56:33.734 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
08:56:33.734 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":1,"result":[]}

08:56:33.735 [pool-3-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (37-byte body)
08:56:43.748 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST http://localhost:8545/ http/1.1
08:56:43.748 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
08:56:43.748 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 103
08:56:43.748 [main] DEBUG org.web3j.protocol.http.HttpService - 
08:56:43.749 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["0x843a487b90055781bab0fba99489889e"],"id":2}
08:56:43.749 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (103-byte body)
08:56:43.752 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (2ms)
08:56:43.752 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
08:56:43.752 [main] DEBUG org.web3j.protocol.http.HttpService - Date: Mon, 13 Nov 2017 08:56:43 GMT
08:56:43.752 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 39
08:56:43.753 [main] DEBUG org.web3j.protocol.http.HttpService - 
08:56:43.753 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":2,"result":true}

08:56:43.753 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (39-byte body)
here
```

Please can you confirm is this is an issue through turning on logging and using web3j 3.1.0 (being released in a few hours).

**Comment by frasierw** [comment] 2017-11-14 01:50
Thanks for the response @conor10 
My question was more about why the program won't exit even after the unsubscribe call. I've tried to run your test code against 3.1.0, but the test won't finish even after "TimeUnit.MINUTES.sleep(1);"

**Comment by frasierw** [comment] 2017-11-14 02:36
Thanks for the response, @conor10 

My original question was why the program won't terminate after unsubscribe call. 

But it's more weird now. If I put the piece of code within a test, the test will eventually finish. However, if I put the same piece of code in the main method of a class, the program will never terminated. Can you please run the following code and see if the program will terminate? I'm using 3.1.0 release.

public class App {

    public static void main(String[] args) throws Exception {
        Web3j web3 = Web3j.build(new HttpService());
        Subscription subscription = web3.blockObservable(true).subscribe(block -> {
            System.out.println("Sweet, block number " + block.getBlock().getNumber() + " has just been created");
        }, Throwable::printStackTrace);
        TimeUnit.SECONDS.sleep(10);
        subscription.unsubscribe();

        System.out.println("here");
        TimeUnit.MINUTES.sleep(1);
    }
}

**Comment by conor10** [comment] 2017-11-15 14:35
The root cause is using a single [ScheduledExecutorService for all filters](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/JsonRpc2_0Web3j.java#L81) in web3j.

If a new ScheduledExecutorService instance was created for every subscription and `scheduledExecutorService.shutdown()` was called along with `cancel` on the [scheduled future](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/protocol/core/filters/Filter.java#L92), the JVM shutdown would be clean.

However, this would result in potentially a large number of threads being created, which could be problematic for Android users. 

Hence I'd recommend you use `System.exit(0)` in your application. This will trigger the shutdown hooks for any [Executors created](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/utils/Async.java) in web3j.

Alternatively, you can provide your own ScheduledExecutorService to web3j when you instantiate it, then shut it down yourself when your application terminates.

**Closed** 2017-11-15 14:35 UTC
Labels: question
