### ISSUE TITLE
web3.ethEstimateGas Fails with insufficient gas error

### ISSUE THREAD

**Issue by geofferyj** [web3j/web3j#1891] opened 2023-04-06 09:47 UTC
# web3.ethEstimateGas Fails with insufficient gas error

## description
estimate gas is failing with the following error
```
I/System.out: 10:40:00.488 [WebSocketConnectReadThread-633] DEBUG org.web3j.protocol.websocket.WebSocketClient - Received message {"jsonrpc":"2.0","id":71,"error":{"code":-32000,"message":"err: insufficient funds for gas * price + value: address 0x55d398326F99059Ff775485246999027B3197956 have 0 want 1 (supplied gas 70010499)"}}
```
heres my estimate gas function in kotlin

```kotlin
    fun estimateTransferGas(to: String, amount: BigDecimal, token: String = ""): Pair<BigInteger, BigInteger> {

        val function = Function(
            "transfer",
            listOf<Type<*>>(
                Address(to),
                Uint256(amount.toBigInteger()),
            ),
            emptyList<TypeReference<*>>(),
        )

        val data = FunctionEncoder.encode(function)
        val tx = if (token.isEmpty()) {
            Transaction(
                "0x55d398326F99059Ff775485246999027B3197956",
                null,
                null,//0.toBigInteger(),
                null,//0.toBigInteger(),
                to,
                1.toBigInteger(),
                token,
            )
        } else {
            Transaction.createEthCallTransaction("0x55d398326F99059Ff775485246999027B3197956", to, data)
//            Transaction.createFunctionCallTransaction("0x55d398326F99059Ff775485246999027B3197956", null, null, null, to, data)
        }

        val gasPrice = web3.ethGasPrice().send().gasPrice
        val gasLimit = web3.ethEstimateGas(tx).send().amountUsed

        return Pair(gasPrice, gasLimit)
    }
```

I've tried everything, please help

## context

The Blockchain is Binance Smart Chain
platform is android

**Comment by geofferyj** [comment] 2023-05-09 02:19
bump

**Comment by NickSneo** [comment] 2023-09-27 06:54
Have you tried it with local blockchain deployment like Ganache? 

Here is a java code working fine for me on Ganache - 
```
Function function = new Function(
               "transfer",
               Arrays.asList(
                       new Address("0xdbef6A4F14B9bD60e37a51AA836b382DDbc5DdD2"),
                       new Uint256(BigInteger.ONE)
               ),
               Collections.emptyList()
       );

       String data = FunctionEncoder.encode(function);

       Transaction tx = Transaction.createEthCallTransaction(
               "0xdbef6A4F14B9bD60e37a51AA836b382DDbc5DdD2",
               "0x0e4eB9f2276aF092889036B04db40235E4E01121",
               data
       );

       EthEstimateGas estimateGas = web3j.ethEstimateGas(tx).send();
       System.out.println(estimateGas.getAmountUsed());
```

It might be an issue with BSC, maybe the account needs to funded with minimum balance? Also I tried to look into Binance API docs but couldn't find it, let us know if you get anything related to it

**Comment by NickSneo** [comment] 2023-10-03 06:04
Closing issue as not a bug, anyone can reopen it incase they face any issue.

**Closed by NickSneo** 2023-10-03 06:04 UTC
Labels: needs-review
