### ISSUE TITLE
Getting error: Empty value (0x) returned from contract when using string[] as a parameter

### ISSUE THREAD

**Issue by kelheor** [web3j/web3j#691] opened 2018-08-31 08:58 UTC
I'm getting this error `org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract` when I'm trying to execute this function:

```
pragma solidity ^0.4.23;
pragma experimental ABIEncoderV2;
...
function stringArrayTest(string[] inputValue) public pure returns(string) {        
        return "Success";
}
```

I'm using Infura. Any ideas on how to fix this error?

**Comment by kelheor** [comment] 2018-10-10 17:05
Still actual...

**Comment by xiaods** [comment] 2018-10-18 07:05
same here

**Comment by iikirilov** [comment] 2018-11-14 15:13
@kelheor can you submit a PR with a breaking test for this please?

**Comment by kelheor** [comment] 2018-11-15 02:56
It's hard for me to create tests inside web3j sources(don't know even where to better place those tests), so I uploaded example project (IntelliJ Idea) to the attachments.
Look at StringIssueApplicationTests class.
[StringIssue.zip](https://github.com/web3j/web3j/files/2583463/StringIssue.zip)

**Comment by AlexandrouR** [comment] 2019-08-02 09:42
ABIEncoderV2 is not supported in web3j. Closing as this is duplicate of #935. Please go there to track the progess of this issue

**Closed by AlexandrouR** 2019-08-02 09:42 UTC
Labels: awaiting-user-input, bug
