### ISSUE TITLE
No virtual method longValueExact() on devices running Android 11 or lower

### ISSUE THREAD

**Issue by sahashuvo** [web3j/web3j#1515] opened 2021-09-29 05:10 UTC
# No virtual method longValueExact() on devices running Android 11 or lower

## Steps To Reproduce

Use on any sample android project and run on devices running Android 11 (API 30) or below.
```java
web3j.ethGetTransactionByHash(txHash);
```

### Expected behavior

Transaction should be parsed by Web3J Properly.

### Actual behavior

```log
2021-09-29 10:59:59.318 14718-14718/com.example.web3jtransactiontest E/AAA: com.fasterxml.jackson.databind.JsonMappingException: No virtual method longValueExact()J in class Ljava/math/BigInteger; or its super classes (declaration of 'java.math.BigInteger' appears in /apex/com.android.art/javalib/core-libart.jar)
        at [Source: (ByteArrayInputStream); line: 1, column: 33221] (through reference chain: org.web3j.protocol.core.methods.response.EthTransaction["result"]->org.web3j.protocol.core.methods.response.Transaction["v"])
```

## Environment

- Web3j version: org.web3j:core:4.8.7-android
- Android version: Android 11 (API 30)

## Additional context
Here is a sample project depicting the error:
https://github.com/sahashuvo/Web3JTransactionTest

Thanks again for your support!

**Comment by sahashuvo** [comment] 2021-09-29 05:13
@AlexandrouR @iikirilov @mohamedelshami @yasseralaa @conor10 

I require your urgent support, hence I would like to request you to,
please consider checking out this issue at your earliest convenience.

Thank you again for your help!

**Comment by AlexandrouR** [comment] 2021-09-29 07:04
HI, @sahashuvo I will look into this.

**Comment by AlexandrouR** [comment] 2021-09-29 11:11
@sahashuvo  The issue has been identified and I am looking at the best course of action to take. The issue is related to the `longValueExact` which we use in two classes.` Transaction`  and `EnsResolver` the issue is as you mentioned that android 11 or later does not have the implementation of this method, it is however seem to be resolved in android 12 (whenever that is released). Change `longValueExact` to `longValue` fixes this issue however there are drawbacks in terms of the accuracy of this conversion. I will come up with a solution soon.

**Comment by AlexandrouR** [comment] 2021-09-29 15:40
PR done it will be fixed in the next release.

**Comment by sahashuvo** [comment] 2021-09-30 04:56
Thanks a lot @AlexandrouR for your swift response. Really appreciate your help! 
Can you please share the tentative schedule for the next web3j-android release?

**Comment by AlexandrouR** [comment] 2021-09-30 07:54
@sahashuvo  We do release snapshots for every push on master so you could use `4.8.7-SNAPSHOT` for you project

**Closed** 2021-10-04 11:48 UTC
Labels: bug

**Comment by Armaan-Ul-Islam** [comment] 2021-10-06 13:03
> @sahashuvo We do release snapshots for every push on master so you could use `4.8.7-SNAPSHOT` for you project


@AlexandrouR Thanks. We really appreciate your quick fix.

Required one more support from your end,

### [Issue](https://github.com/web3j/web3j/issues/1515): "Transaction response parsing error (frequency: always)" [FIXED with [the commit](https://github.com/web3j/web3j/commit/35724dc678d3b2a6ccc0028157e580267b9a57d3) ]
### Requriment: A new Android **release** for Web3J (say 4.8.8 or 4.8.8-android)

### Reasons: 
* **For the Sake of Developers using Web3J**: This issue can be considered a major issue as all the devices running on Android 11 or below (~almost all android devices) will not be able to retrieve transactions properly without this fix. We expect most developers to import a publicly released version, rather than snapshots. So this fix should be released as soon as possible.

* **For the Sake of My project**: The model/Architecture used in my project (an android library) is that we do not package/export the Web3J library ourselves. Thus, developers have to import the publicly released version of Web3J in their 'build.gradle' files to use our SDK/services. (which also showcases Web3J library to all :+1: ). So in our case, we urgently require this fix to go public. (We've tried jitpack Snapshots, but facing challenges in many cases)
