### ISSUE TITLE
Make word list used for mnemonic configurable

### ISSUE THREAD

**Issue by alessandroponzo** [web3j/web3j#886] opened 2019-03-07 11:45 UTC
I need to add new mnemonic language word list, so I cloned the web3j locally. I want to import it as module in Android Studio doing File->New->Import Module but I got this error.

``  ERROR: Could not find method compile() for arguments [project ':utils'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
``

**Comment by iikirilov** [comment] 2019-03-07 14:10
We should make the word list configurable. At the moment it is hard coded.
 See
`MnemonicUtils.populateWordList()`

**Comment by iikirilov** [comment] 2019-07-19 00:04
Closing as duplicate of #919 

A proposal has been made on the work that needs to be done there

**Closed by iikirilov** 2019-07-19 00:04 UTC
Labels: enhancement
