### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]

### ISSUE THREAD

**Issue by fulldecent** [web3j/web3j#1369] opened 2021-02-19 02:18 UTC
# _Bug_title_
Signing a message produces the error:

> Exception in thread "main" java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]

## Steps To Reproduce

Using this snippet:

```java
    private final byte[] seed;
    seed = MnemonicUtils.generateSeed("apple apple apple apple apple apple apple apple apple apple apple apple", null);

    String claim = "hello";
    System.out.println("Preparing claim");
    System.out.println(claim);
    System.out.println("");

    System.out.println("Signing");
    Credentials credentials = Credentials.create(bytesToHex(seed));
    System.out.println("Address: " + credentials.getAddress());
    Sign.SignatureData signature = Sign.signPrefixedMessage(claim.getBytes(), credentials.getEcKeyPair());
    System.out.println("R: " + Numeric.toHexString(signature.getR()));
    System.out.println("S: " + Numeric.toHexString(signature.getS()));
    System.out.println("V: " + Numeric.toHexString(signature.getV()));
```

P.S. is there a nice way to make minimal test cases in Java land that are actually reproducible other than starting a whole Maven project, POM.xml, build scripts, etc.?

### Expected behavior

The message is signed.

### Actual behavior

Error

> Exception in thread "main" java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]
>	at org.bouncycastle.crypto.params.ECDomainParameters.validatePrivateScalar(Unknown Source)
>	at org.bouncycastle.crypto.params.ECPrivateKeyParameters.<init>(Unknown Source)
>	at org.web3j.crypto.ECKeyPair.sign(ECKeyPair.java:55)
>	at org.web3j.crypto.Sign.signMessage(Sign.java:83)
>	at org.web3j.crypto.Sign.signPrefixedMessage(Sign.java:67)
>	at io.genobank.PermitteeSigner.sign(PermitteeSigner.java:71)
>	at io.genobank.Main.main(Main.java:157)

## Environment

_Describe the environment in which the issue occurs_

- Web3j version 5.0.0
- Java or Android version Java `java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)`
- Operating System `uname -a       
Darwin xxx.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64` Mac / 11.2.1 (20D74)

## Additional context

None yet

**Comment by fulldecent** [comment] 2021-02-19 05:12
More references. Mostly for myself:

- https://github.com/web3j/web3j/issues/208
- https://github.com/web3j/web3j/blob/master/crypto/src/main/java/org/web3j/crypto/Sign.java#L56

**Comment by AlexandrouR** [comment] 2021-02-19 09:10
@fulldecent  Hi, the latest stable version of web3j is 4.8.4 version 5 release was by mistake could you try with 4.8.4 and let me know if the issue persists

**Comment by fulldecent** [comment] 2021-02-19 20:27
Thank you, got it. I have updated pom.xml to use version 4.8.4 and reinstalled.

This is still producing the same error.

Here is my complete implementation which is causing the problem: https://github.com/Genobank/genobankj/blob/main/src/main/java/io/genobank/cryptography/PermitteeSigner.java#L34-L37

The line is commented out that is the crashing line.

Is there a nicer way I can isolate this to share the test case or does this show you what's up?

**Comment by fulldecent** [comment] 2021-02-21 18:58
I don't know what I did wrong. And I don't know why this works. But here is what I am now using that does not crash.

# This crashes, bad:

```java
    // Make claim
    String claim = Hash.sha3("a claim");
    System.out.println("Claim:       " + claim);

    // Load wallet, bad way    
    byte[] seed = MnemonicUtils.generateSeed("apple apple apple apple apple apple apple apple apple apple apple apple", null);
    Credentials credentials = Credentials.create(Numeric.toHexString(seed));
    System.out.println("Address:     " + credentials.getAddress());

    // Sign
    Sign.SignatureData signature = Sign.signPrefixedMessage(claim.getBytes(), credentials.getEcKeyPair());
    System.out.println("R:           " + Numeric.toHexString(signature.getR()));
    System.out.println("S:           " + Numeric.toHexString(signature.getS()));
    System.out.println("V:           " + Numeric.toHexString(signature.getV()));
```

# This does not crash, good

```java
    String password = null;
    String mnemonic = "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat";
    String message = "a message";

    // How to load an Ethereum wallet explained at https://gitter.im/web3j/web3j?at=5cb437ba31aec969e8aaed08
    // Test case https://www.trufflesuite.com/docs/truffle/getting-started/using-truffle-develop-and-the-console
    Bip32ECKeyPair masterKeypair = Bip32ECKeyPair.generateKeyPair(MnemonicUtils.generateSeed(mnemonic, password));
    int[] path = {44 | HARDENED_BIT, 60 | HARDENED_BIT, 0 | HARDENED_BIT, 0,0};
    Bip32ECKeyPair x = Bip32ECKeyPair.deriveKeyPair(masterKeypair, path);
    Credentials credentials = Credentials.create(x);
    System.out.println("Address:     " + credentials.getAddress());

    // Sign
    Sign.SignatureData signature = Sign.signPrefixedMessage(message.getBytes(), credentials.getEcKeyPair());
    System.out.println("R:           " + Numeric.toHexString(signature.getR()));
    System.out.println("S:           " + Numeric.toHexString(signature.getS()));
    System.out.println("V:           " + Numeric.toHexString(signature.getV()));

```

---

# Next steps

I have solved my problem here.

@AlexandrouR could you please help to decide if this above represents an actual problem (issue) or not (close issue, user error).

**Comment by NickSneo** [comment] 2023-03-30 07:32
Hey @fulldecent , below are the steps to create credentials/ECKeyPair/Wallet - 

```     
// Make claim
String claim = "a claim";

String mnemonic = "apple apple apple apple apple apple apple apple apple apple apple apple";
byte[] seed = MnemonicUtils.generateSeed(mnemonic, null);
```

1. Using Bip39Wallet - 

```
// Generate the wallet
Bip39Wallet wallet = WalletUtils.generateBip39WalletFromMnemonic("", mnemonic, new File("wallet-dir"));

// Load the credentials from the wallet
Credentials credential = WalletUtils.loadBip39Credentials("", wallet.getMnemonic());
```

2. Using Credentials (which was crashing for you, the correct method is below) - 
a) `Credentials cred = Credentials.create(ECKeyPair.create(Hash.sha256(seed)));`
b) `Credentials cred2 = Credentials.create(Numeric.toHexString(Hash.sha256(seed)));`

3. Using ECKeyPair - 
`ECKeyPair ecKeyPair = ECKeyPair.create(Hash.sha256(seed));`

Why it was crashing for you? 
- You were not hashing the seed before giving into Numeric.tohexString(), the correct way is - `Numeric.toHexString(Hash.sha256(seed))`. This resolves the issue.
Source - 
https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/crypto/WalletUtils.java#L114

Closing the issue as not a bug. Thanks!

**Closed** 2023-03-30 07:33 UTC
Labels: bug, needs-review
