### ISSUE TITLE
Android library is impossible to use due to apache httpclient incompatibility

### ISSUE THREAD

**Issue by vikulin** [web3j/web3j#24] opened 2016-11-29 19:42 UTC
Android studio gives me:
Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.2 is ignored for debug as it may be conflicting with the internal version provided by Android.

At runtime app throws

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClients;
                      at org.web3j.protocol.http.HttpService.<init>(HttpService.java:47)
                      at org.vikulin.etherwallet.DrawerActivity.onClick(DrawerActivity.java:131)
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                      at android.view.View.performClick(View.java:5637) 
                      at android.view.View$PerformClick.run(View.java:22429) 
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.HttpClients" on path: DexPathList

**Comment by vikulin** [comment] 2016-11-29 19:46
Used import compile 'org.web3j:core-android:1.0.8'

**Comment by vikulin** [comment] 2016-11-29 19:53
Manual jar including affected by https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=184323#makechanges

**Comment by conor10** [comment] 2016-11-30 21:54
Closing following merge of your pull request.

**Closed by conor10** 2016-11-30 21:54 UTC

**Comment by VictorCruzIsc** [comment] 2017-05-03 20:02
Hi, I'm not part of the project however I'm also programming an app that is giving me the same problem as the one described above in your issue.

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClients;

I'm using API 23 could you please help me in order to avoid this issue? What was you solution?

Thanks in advance!

**Comment by conor10** [comment] 2017-05-04 00:10
What version of web3j-android are you using?
