### ISSUE TITLE
transaction Observable BigInteger out of int range

### ISSUE THREAD

**Issue by ghost** [web3j/web3j#182] opened 2017-10-04 11:33 UTC
I added dependency of web3j from https://github.com/web3j/web3j-spring-boot-starter

Then created a service and written :

    @Service
    public class Web3jServiceImpl {
     
        @Autowired
        private Web3j web3j;
     
        public void getBlockNumber() {
    		logger.debug("get block number method");
    		web3j.blockObservable(false).subscribe(block -> {
    			logger.debug("block number: {}", block.getBlock().getNumber() + " has just been created");
    		}, Throwable::printStackTrace);
    	}
    
      public void getTxInfo(){
        web3j.transactionObservable().subscribe(tx -> {
    			logger.debug("transaction info: {}",tx);
       }, Throwable::printStackTrace);
     }
    }

I am getting block number when any block is created in private block chain of ethereum, but In transaction observable getting `BigInteger out of int range` exception.

log is:

    com.fasterxml.jackson.databind.JsonMappingException: BigInteger out of int range
     at [Source: org.apache.http.conn.EofSensorInputStream@6f12b9e; line: 1, column: 1770] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"]) (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"]->org.web3j.protocol.core.methods.response.EthBlock$Block["transactions"])
    	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
    	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1600)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
    	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
    	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
    	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:981)
    	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:562)
    	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:553)
    	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
    	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
    	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924)
    	at org.web3j.protocol.http.HttpService.lambda$getResponseHandler$20(HttpService.java:89)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
    	at org.web3j.protocol.http.HttpService.send(HttpService.java:67)
    	at org.web3j.protocol.core.Request.send(Request.java:69)
    	at org.web3j.protocol.core.Request.lambda$observable$8(Request.java:80)
    	at rx.Observable.unsafeSubscribe(Observable.java:10142)
    	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
    	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
    	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
    	at org.web3j.protocol.core.filters.BlockFilter.process(BlockFilter.java:32)
    	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:82)
    	at org.web3j.protocol.core.filters.Filter.lambda$run$9(Filter.java:48)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: com.fasterxml.jackson.databind.RuntimeJsonMappingException: BigInteger out of int range
     at [Source: org.apache.http.conn.EofSensorInputStream@6f12b9e; line: 1, column: 1770] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"])
    	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:194)
    	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:537)
    	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:520)
    	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
    	... 33 more
    Caused by: com.fasterxml.jackson.databind.JsonMappingException: BigInteger out of int range
     at [Source: org.apache.http.conn.EofSensorInputStream@6f12b9e; line: 1, column: 1770] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"])
    	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
    	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:551)
    	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:532)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:108)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
    	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:277)
    	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:192)
    	... 38 more
    Caused by: java.lang.ArithmeticException: BigInteger out of int range
    	at java.math.BigInteger.intValueExact(BigInteger.java:4550)
    	at org.web3j.protocol.core.methods.response.Transaction.setV(Transaction.java:220)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:106)
    	... 42 more

**Comment by conor10** [comment] 2017-10-16 08:47
There was an issue in web3j 2.3.0 which the Spring Boot Starter uses. Please can you try using 2.3.1, or wait until the 3.0 web3j release is out in the next week or two, as I'll push out a new build of the Spring Boot Starter too.

**Comment by conor10** [comment] 2017-11-08 19:58
Please can you confirm if this is fixed in the 3.0 release?

**Comment by ckrsingh** [comment] 2017-11-09 08:43
Hi @conor10 , Still it exists,
the new log is:

```
com.fasterxml.jackson.databind.JsonMappingException: BigInteger out of int range
 at [Source: buffer(okhttp3.internal.http1.Http1Codec$FixedLengthSource@74c03a07).inputStream(); line: 1, column: 1769] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"]) (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"]->org.web3j.protocol.core.methods.response.EthBlock$Block["transactions"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1600)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:981)
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:561)
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:552)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924)
	at org.web3j.protocol.Service.send(Service.java:32)
	at org.web3j.protocol.core.Request.send(Request.java:68)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at org.web3j.protocol.core.RemoteCall.lambda$observable$11(RemoteCall.java:51)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at org.web3j.protocol.core.filters.BlockFilter.process(BlockFilter.java:32)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:84)
	at org.web3j.protocol.core.filters.Filter.lambda$run$10(Filter.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.RuntimeJsonMappingException: BigInteger out of int range
 at [Source: buffer(okhttp3.internal.http1.Http1Codec$FixedLengthSource@74c03a07).inputStream(); line: 1, column: 1769] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"])
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:194)
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:536)
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:519)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	... 30 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: BigInteger out of int range
 at [Source: buffer(okhttp3.internal.http1.Http1Codec$FixedLengthSource@74c03a07).inputStream(); line: 1, column: 1769] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:551)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:532)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:277)
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:192)
	... 35 more
Caused by: java.lang.ArithmeticException: BigInteger out of int range
	at java.math.BigInteger.intValueExact(BigInteger.java:4550)
	at org.web3j.protocol.core.methods.response.Transaction.setV(Transaction.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:106)
	... 39 more
com.fasterxml.jackson.databind.JsonMappingException: BigInteger out of int range
 at [Source: buffer(okhttp3.internal.http1.Http1Codec$FixedLengthSource@dd12fdc).inputStream(); line: 1, column: 1769] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"]) (through reference chain: org.web3j.protocol.core.methods.response.EthBlock["result"]->org.web3j.protocol.core.methods.response.EthBlock$Block["transactions"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1600)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:981)
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:561)
	at org.web3j.protocol.core.methods.response.EthBlock$ResponseDeserialiser.deserialize(EthBlock.java:552)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924)
	at org.web3j.protocol.Service.send(Service.java:32)
	at org.web3j.protocol.core.Request.send(Request.java:68)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at org.web3j.protocol.core.RemoteCall.lambda$observable$11(RemoteCall.java:51)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at org.web3j.protocol.core.filters.BlockFilter.process(BlockFilter.java:32)
	at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:84)
	at org.web3j.protocol.core.filters.Filter.lambda$run$10(Filter.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.RuntimeJsonMappingException: BigInteger out of int range
 at [Source: buffer(okhttp3.internal.http1.Http1Codec$FixedLengthSource@dd12fdc).inputStream(); line: 1, column: 1769] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"])
	at com.f
```asterxml.jackson.databind.MappingIterator.next(MappingIterator.java:194)
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:536)
	at org.web3j.protocol.core.methods.response.EthBlock$ResultTransactionDeserialiser.deserialize(EthBlock.java:519)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	... 30 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: BigInteger out of int range
 at [Source: buffer(okhttp3.internal.http1.Http1Codec$FixedLengthSource@dd12fdc).inputStream(); line: 1, column: 1769] (through reference chain: org.web3j.protocol.core.methods.response.EthBlock$TransactionObject["v"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:551)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:532)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:277)
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:192)
	... 35 more
Caused by: java.lang.ArithmeticException: BigInteger out of int range
	at java.math.BigInteger.intValueExact(BigInteger.java:4550)
	at org.web3j.protocol.core.methods.response.Transaction.setV(Transaction.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:106)
	... 39 more

**Comment by ckrsingh** [comment] 2017-11-09 08:44
I tested it on core 3.0.2 as well with dependency 

```
<dependency>
			<groupId>org.web3j</groupId>
			<artifactId>core</artifactId>
			<version>3.0.2</version>
		</dependency>
```

**Comment by fcorneli** [comment] 2018-04-02 10:05
This is the chain id V value parsing that fails.

**Comment by iikirilov** [comment] 2018-11-09 11:46
Is this still an issue?

**Comment by AlexandrouR** [comment] 2019-07-12 10:00
closed due to inactivity.

**Closed by AlexandrouR** 2019-07-12 10:00 UTC
Labels: awaiting-user-input
