### ISSUE TITLE
Error building the java wrapper

### ISSUE THREAD

**Issue by developerRojina** [web3j/web3j#1855] opened 2023-01-31 15:18 UTC
# Build Failed
When generating the Java wrapper file from the web3j command terminal, the build is failed with incompatile types.

## Steps To Reproduce
I exported the json abi from the following url:
[Url](https://api.ftmscan.com/api?module=contract&action=getabi&address=0x261ABeFd8E8895d9E68421888e7bDF8042E6A96F)
and added it in my project
Generated the wrapper by using the following command:
web3j generate solidity -a path_to_json_file -o /my_project_path/app/src/main/java -p package_name
The file generated successfully but  the build failed with incompatible types

### Expected behavior
Successful file generation
Successful build of the application
Ability to access the contract functions

### Actual behavior
App build fails

## Environment

- Web3j version :1.4.2
- Java version: openJdk 16.0.2
- Operating System : Mac M1

## Additional context
Logs:
`'staticExtractEventParametersWithLog(org.web3j.abi.datatypes.Event, org.web3j.protocol.core.methods.response.Log)' in 'org.web3j.tx.Contract' cannot be applied to '(org.web3j.abi.datatypes.Event, org.web3j.protocol.core.methods.response.TransactionReceipt)'`

- [fantomscan](https://api.ftmscan.com/api?module=contract&action=getabi&address=0x261ABeFd8E8895d9E68421888e7bDF8042E6A96F) references

**Comment by JeneaVranceanu** [comment] 2023-02-13 15:43
The issue is in the codegen: https://github.com/web3j/web3j/blob/bbecec8b9885a5b0bc2b5a09d04af50bab5fe071/codegen/src/main/java/org/web3j/codegen/SolidityFunctionWrapper.java#L1793

![Screenshot 2023-02-13 at 17 39 44](https://user-images.githubusercontent.com/36865532/218502991-99dd0fbd-a526-4010-bcff-f52b235f02fe.png)


The wrong function is being used. There is no `staticExtractEventParametersWithLog` that is able to process `TransactionReceipt`. 

But at the same time there is `protected List<EventValuesWithLog> extractEventParametersWithLog` which is not static but completely fits the purpose and the given arguments.

![Screenshot 2023-02-13 at 17 40 34](https://user-images.githubusercontent.com/36865532/218503748-aafcf588-4dc0-4b55-88ef-735d7559ef59.png)

**Comment by alexgutjahr** [comment] 2023-02-27 15:26
We have experienced the same in another suite of contracts.
- Web3j version: 1.4.2
- Java version:
-- openjdk version "17.0.4" 2022-07-19 LTS
-- OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)
-- OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)

**Comment by fooock** [comment] 2023-03-06 20:20
using the latest library version solved the problem 
```
web3j = { module = "org.web3j:core", version = "4.9.7" }
```

**Comment by NickSneo** [comment] 2023-10-19 01:23
Closing as it got fixed in web3j 4.9.7 as confirmed by the users.

**Closed by NickSneo** 2023-10-19 01:23 UTC
Labels: bug
