### ISSUE TITLE
java.lang.NoClassDefFoundError for web3jService

### ISSUE THREAD

**Issue by NosWiz** [web3j/web3j#715] opened 2018-09-21 11:46 UTC
I  get an error when trying to run the jar i successfully export with gradle build. web3j is globally installed with linuxbrew, PATH is set for web3j. compiling gives no warnings or errors. is this maybe a gradle or an web3j problem? or does it not work with the java version i use? (java 8)

```
package org.cweitzel.carob;

import org.cweitzel.wrapper.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.web3j.crypto.Credentials;
import org.web3j.crypto.WalletUtils;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.TransactionReceipt;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.Contract;
import org.web3j.tx.ManagedTransaction;
import org.web3j.tx.Transfer;
import org.web3j.utils.Convert;
import org.web3j.utils.Numeric;


public class Deploy {
  // log for status tracking of deployment of contracts
  private static final Logger logger = LoggerFactory.getLogger(Deploy.class);

  public static void main (String[] args) throws Exception {
    new Deploy().run();
  }

  private void run() throws Exception {
    // create new web3j instance to connect to remote nodes on the network
    Web3j web3j = Web3j.build(new HttpService("http://localhost:8545"));
    logger.info("Connected to Ethereum client version: "
      + web3j.web3ClientVersion().send().getWeb3ClientVersion());
    Credentials credentials =
      WalletUtils.loadCredentials( [...]);

    // deploy contracts [...]
}
```

my build is made with gradle. build.gradle file:

```
group 'org.web3j'
version '0.1.0'

// Apply the java plugin to add support for Java
apply plugin: 'java'

// tell the java compiler to use java 9
sourceCompatibility = 1.9
targetCompatibility = 1.9


repositories {
  jcenter()
  mavenCentral()
}

ext {
  web3jVersion = '3.5.0'
  // logbackVersion = '1.2.3'
  junitVersion = '4.12'
}

dependencies {

  compile "org.web3j:core:$web3jVersion",
          // "ch.qos.logback:logback-core:$logbackVersion",
          // "ch.qos.logback:logback-classic:$logbackVersion"
          "org.slf4j:slf4j-api:1.7.21"
  testCompile "junit:junit:$junitVersion"

  // The production code uses the SLF4J logging API at compile time
  compile 'org.slf4j:slf4j-api:1.7.21'.
}

// name of the jar file
// this will render CaRoB-0.1.0.jar
jar {
  baseName = 'CaRoB'
  version = '0.1.0'
  manifest {
    attributes("Implementation-Title": "CaRoB",
              "Implementation-Version": version,
              "Main-Class": "org.cweitzel.carob.Deploy")
  }
}
```

when i run the jar i get:

```
noswiz@NosWiz-Lappy:~/Documents/uni/ethereum/CaRoB/CaRoB$ java -jar build/libs/CaRoB-0.1.0.jar 
Error: Unable to initialize main class org.cweitzel.carob.Deploy
Caused by: java.lang.NoClassDefFoundError: org/web3j/protocol/Web3jService
noswiz@NosWiz-Lappy:~/Documents/uni/ethereum/CaRoB/CaRoB$
```

any suggestions why its not working? :/ i already spent hours on this and got pressure due to project deadline

i already tried:
*  some other ways to include the web3j into build.gradle and the local settings.gradle (which i deleted, its not existing at the moment)
*  renaming package
*  java 8 and 9 (i am using the openjdk's)

**Comment by iikirilov** [comment] 2018-11-09 11:15
@NosWiz Sorry, appreciate this is probably coming after your deadline. Did you manage to fix it?

If not, please use web3j 3.6.0

**Comment by tommymato** [comment] 2019-01-04 11:56
Hi @iikirilov, I'm getting the same error. My code does not reference the Web3jService. Like @NosWiz I do not get any compiler errors. I've tried using 3.6.0 and the latest 4.1.0 - same error. I'm getting a NoClassDefFoundError org/Web3j/protocol/Web3jService.

I've got skeleton code - the imports for org.web3j.protocol.Web3j; and org.web3j.protocol.http.HttpService; and one line of executable code as follows:

Web3j web3j = Web3j.build(new HttpService("http://silverstone:8545"));

Do you know if there is a workaround for this? TIA

**Comment by tommymato** [comment] 2019-01-04 22:54
Update (to help others who may run into the same problem): The problem is not related to Web3jService - that just happens to be the first class that is called in my case. The real reason is it can't find any dependency classes! For some reason Maven is not copying the dependencies into the executable jar.

Maven really is the idiot child of the Apache family - it needs to be led around and told what to do at all times :-)

**Comment by snazha-blkio** [comment] 2019-02-10 20:32
@tommymato , thanks for providing the details. Closing this issue.

**Closed by snazha-blkio** 2019-02-10 20:32 UTC
Labels: awaiting-user-input
