### ISSUE TITLE
Got Error:trouble processing "java/lang/SafeVarargs.class": under Android Studio after upgrade web3j lib from 2.2.1 to 3.1.1

### ISSUE THREAD

**Issue by vikulin** [web3j/web3j#281] opened 2017-12-15 13:04 UTC
Error:trouble processing "java/lang/SafeVarargs.class":
Error:Ill-advised or mistaken usage of a core class (java.* or javax.*)
Error:when not building a core library.
Error:This is often due to inadvertently including a core library file
Error:in your application's project, when using an IDE (such as
Error:Eclipse). If you are sure you're not intentionally defining a
Error:core class, then this is the most likely explanation of what's
Error:going on.
Error:However, you might actually be trying to define a class in a core
Error:namespace, the source of which you may have taken, for example,
Error:from a non-Android virtual machine project. This will most
Error:assuredly not work. At a minimum, it jeopardizes the
Error:compatibility of your app with future versions of the platform.
Error:It is also often of questionable legality.
Error:If you really intend to build a core library -- which is only
Error:appropriate as part of creating a full virtual machine
Error:distribution, as opposed to compiling an application -- then use
Error:the "--core-library" option to suppress this error message.
Error:If you go ahead and use "--core-library" but are in fact
Error:building an application, then be forewarned that your application
Error:will still fail to build or run, at some point. Please be
Error:prepared for angry customers who find, for example, that your
Error:application ceases to function once they upgrade their operating
Error:system. You will be to blame for this problem.
Error:If you are legitimately using some code that happens to be in a
Error:core package, then the easiest safe alternative you have is to
Error:repackage that code. That is, move the classes in question into
Error:your own package namespace. This means that they will never be in
Error:conflict with core system classes. JarJar is a tool that may help
Error:you in this endeavor. If you find that you cannot do this, then
Error:that is an indication that the path you are on will ultimately
Error:lead to pain, suffering, grief, and lamentation.
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

**Comment by maratsubkhankulov** [comment] 2017-12-17 01:21
Also experiencing this issue, worked around it by downgrading to 3.0.1-android

**Comment by conor10** [comment] 2017-12-17 14:31
What dependencies does the project use?

@joanesespanol - do you have any thoughts?

**Comment by joanesespanol** [comment] 2017-12-18 07:43
Hey guys,

The SafeVarargs annotation was added in the master branch to a few classes/methods to address compilation warnings.  This was fine in the master branch, which is using Java 8, however it caused a bunch of problems in the android branch which remains on Java 6 but the SafeVarags annotation was introduced only in Java 7.

To remedy the problem in the android branch, a copy of the SafeVarargs annotation class was created, in the java.lang package (https://github.com/web3j/web3j/blob/android/utils/src/main/java/java/lang/SafeVarargs.java)... that way we were able to use the exact same classes on both branches and benefit from the SafeVargs annotation.

The cause of the problem mentioned in this thread is that the "cloned" java.lang.SafeVargs class is included in the utils-3.x.y-android.jar file, which causes the "class in a core namespace" panic in other projects.  I think we can do two things:
  - change the RetentionPolicy on the annotation to RetentionPolicy.SOURCE to ensure annotated classes do not retain it once compiled
  - modify the gradle configuration of the utils module to not include the "cloned" SafeVargs class (since it is only used at compile time, this should work and solve the issue)

**Comment by joanesespanol** [comment] 2017-12-18 07:45
Here is what the changes would look like:
<pre>
diff --git a/utils/src/main/java/java/lang/SafeVarargs.java b/utils/src/main/java/java/lang/SafeVarargs.java
index 10421e8b..4352524d 100644
--- a/utils/src/main/java/java/lang/SafeVarargs.java
+++ b/utils/src/main/java/java/lang/SafeVarargs.java
@@ -92,6 +92,6 @@ import java.lang.annotation.*;
 // changed from RUNTIME to CLASS, so it is not causing any problems at runtime.
 
 @Documented
-@Retention(RetentionPolicy.CLASS)
+@Retention(RetentionPolicy.SOURCE)
 @Target({ElementType.CONSTRUCTOR, ElementType.METHOD})
 public @interface SafeVarargs {}
</pre>
<pre>
diff --git a/utils/build.gradle b/utils/build.gradle
index bdd3124c..b73a686e 100644
--- a/utils/build.gradle
+++ b/utils/build.gradle
@@ -4,3 +4,7 @@ description 'Minimal set of web3j utility classes'
 dependencies {
     compile "com.madgag.spongycastle:prov:$spongycastleVersion"
 }
+
+jar {
+    exclude('java/lang/**')
+}
</pre>

Unfortunately, I am currently traveling and don't have all my development environment setup with me here.  @conor10 do you think you could try these diffs above?  If not, I can take a look when I come back in 2-3 days.

**Comment by conor10** [comment] 2017-12-19 08:02
I'm fine to wait.

@maratsubkhankulov  & @vikulin hope this is ok.

**Comment by maratsubkhankulov** [comment] 2017-12-19 08:04
I'm good for now, 3.0.1-android works for the moment.

**Comment by Bhoomika06** [comment] 2017-12-20 11:55
Hello, Can you please tell me, how you got solution?? I am finding same Problem with my app.

**Comment by joanesespanol** [comment] 2017-12-20 16:58
Created a PR to address the problem: https://github.com/web3j/web3j/pull/287.

@vikulin @maratsubkhankulov, if you could check that it solves the problem on Android platforms, that would be great!

**Comment by maratsubkhankulov** [comment] 2017-12-23 01:33
@joanesespanol is that available in the maven package? When I switched back to 3.1.1-android I got the same error.

**Comment by joanesespanol** [comment] 2017-12-23 01:53
@maratsubkhankulov I don't think the code changes have been merged/released yet, but they are available in the PR mentioned above (https://github.com/web3j/web3j/pull/287).  Are you able to pull it down and build it locally?

**Comment by conor10** [comment] 2018-03-02 12:14
3.3.1-android release has gone out. Please reopen if still an issue.

**Closed by conor10** 2018-03-02 12:14 UTC
