### ISSUE TITLE
Different privateKey generated by Mnemonic comparing to other libraries

### ISSUE THREAD

**Issue by lhtriet** [web3j/web3j#919] opened 2019-04-25 02:25 UTC
To get privateKey from Mnemonic, I use: ECKeyPair.create(sha256(seed))

But it creates a different privateKey from the same mnemonic using TrustKeystore in iOS (TrustKeystore generates the correct privateKey comparing to https://iancoleman.io/bip39/)

I did some research and figure out that I need to do something with the configuration of how mnemonic is used. Can you please guide me. Thank you!

**Comment by iikirilov** [comment] 2019-04-26 19:41
Workaround - I would appreciate a PR in web3j to encapsulate this.

```
Bip32ECKeyPair masterKeypair = Bip32ECKeyPair.generateKeyPair(MnemonicUtils.generateSeed("XXXXXXX", null));
int[] path = {44 | HARDENED_BIT, 60 | HARDENED_BIT, 0 | HARDENED_BIT, 0,0};
Bip32ECKeyPair  x = Bip32ECKeyPair.deriveKeyPair(masterKeypair, path);
Credentials credentials = Credentials.create(x);
System.out.println(credentials.getAddress());
```

**Comment by iikirilov** [comment] 2019-04-26 19:41
Didn't mean to close it

**Comment by razzbee** [comment] 2019-05-18 22:31
I get the reason why, other wallets providers (mostly those who uses javascript libaray ) uses a different path compared to web3j, from my digging and observation, web3j borrowed it implementation from bitcoinj so below is the path difference :

web3j & bitcoinj ->   // m/44'/60'/0'/0 (as commented in org/web3j/crypto/Bip44WalletUtils.java)
metamask, blockchain.com & other javascript based libs -> "m/44'/60'/0'/0/0"

How the test was conducted : 
```js 
const ethers = require('ethers');

const mnemonic = "feed scrub chase quarter large wire bench swift embody forum page axis"
const path = "m/44'/60'/0'/0/0"
const wallet = ethers.Wallet.fromMnemonic(mnemonic,path);

console.log(wallet)
```
to reproduce the result install  ethers (yarn add ethers)

**Comment by razzbee** [comment] 2019-05-18 23:17
Well, I have solved it, if you want to support metamask and other wallet, use this : 
```java 
     val mnemonic = "some key phrase"

      val seed = MnemonicUtils.generateSeed(mnemonic,"")

        val masterKeyPair = Bip32ECKeyPair.generateKeyPair(seed)

        val bip44Keypair = Bip32ECKeyPair.deriveKeyPair(masterKeyPair, path)

        val credentials = Credentials.create(bip44Keypair)

        println(credentials.address)
```

**Comment by iikirilov** [comment] 2019-07-17 19:14
Reopening because I think this can be made a lot easier to configure in web3j.

I think a PR should be made to change the default behavior of web3j to be consistent with other ethereum libraries.

It should also be super easy to configure for other use-cases.

**Closed** 2020-10-30 13:29 UTC
Labels: awaiting-pr

**Comment by conor10** [comment] 2020-11-12 14:40
This issue has been mentioned on **Web3 Labs Community**. There might be relevant details there:

https://community.web3labs.com/t/web3j-v4-8-0-released/112/1
