### ISSUE TITLE
Is passing struct as argument in solidity contract supported in web3j?

### ISSUE THREAD

**Issue by katastreet** [web3j/web3j#653] opened 2018-07-30 10:44 UTC
I am using experimental ABIEncoderV2 to pass struct as argument as 

   ```
 struct messageDetails{
        address receiver;
        address postman;
        uint timestamp;
        }
    
    struct nonceDetails{
        bytes encryptedNonce;
        bytes32 decryptor;
        uint timestamp;
    }
    
    function setGoldenHash(address receiver, bytes32 hash, messageDetails mDetails, nonceDetails nDetails) public returns(bool success);
```
and getting the error
```
Generating generated.GoldStoreInterface ... Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported type encountered: tuple
	at org.web3j.abi.datatypes.generated.AbiTypes.getType(AbiTypes.java:221
```

**Comment by abdusamed91** [comment] 2018-08-16 04:34
In my case, the smart contract only has the arguments and the issue arising when trying to retrieve the value of the field values. The smart contract wrapper code during `contractName.deploy(...).send()`, result in the contract instance to have no parameter values! The smart contract can be deployed successfully using MIST and tested fine on Remix. The only problem is if I deploy the contract  on the private blockchain, *

**The field values itself are null** i.e **returned '0x'**. The odd thing is when I check the `input data` of the transaction, those arguments parameters are sent to the blockchain to be added to the smart contract. But the last step - adding the data to the smart contract - never ends. The smart contract has been minded and all. 

Help will be greatly appreciated.

**Comment by katastreet** [comment] 2018-08-16 07:41
@abdusamed91 if your are using your own private blockchain, then i think you should mine the transaction yourself and introduce it to your blockchain. Maybe the transaction is pending and never introduced to the blockchain.

**Comment by branciard** [comment] 2018-08-23 13:30
I suppose new ABIEncoderV2 and struct in args is not yet supported in current realease of web3j ? For web3.js, it has just been merged to be in future release of web3.js according to this issue : https://github.com/ethereum/web3.js/issues/1241

**Comment by abdusamed91** [comment] 2018-08-23 18:07
@katastreet I have been trying to mine the transaction  myself but it wasn't being deployed beyond Web3j to the the Ethereum client itself. It was as if web3j was calculating the cost prior to deploying it to the chain. The way I resolved it and I have no idea why it worked was to compile the contract on another machine and use Web3j 3.3 instead.

**Comment by katastreet** [comment] 2018-10-07 02:37
What i did was, i broke down the struct on functions argument and then created a struct inside the implementation of the function. An extra two lines of code for every function using struct as an argument.

**Comment by iikirilov** [comment] 2018-10-24 17:43
Not yet #368

**Comment by iikirilov** [comment] 2019-08-20 14:13
duplicate of #935

**Closed by iikirilov** 2019-08-20 14:13 UTC
Labels: awaiting-pr
