### ISSUE TITLE
Cannot sign msg when msg length over 32 chars

### ISSUE THREAD

**Issue by markusbug** [web3j/web3j#1850] opened 2023-01-13 18:54 UTC
# Cannot sign msg when msg length over 32
Web3j is throwing a RuntimeException with message "Could not construct a recoverable key. Are your credentials valid?" when the message that has to be signed is longer than 32 characters. 

## Steps To Reproduce
```java
// message is a String with more than 32 characters
byte[] messageBytes = message.getBytes(StandardCharsets.UTF_8);
Sign.SignatureData signature = Sign.signMessage(messageBytes, credentials.getEcKeyPair(), false);

byte[] signedMessage = new byte[65];
System.arraycopy(signature.getR(), 0, signedMessage, 0, 32);
System.arraycopy(signature.getS(), 0, signedMessage, 32, 32);
System.arraycopy(signature.getV(), 0, signedMessage, 64, 1);
String hexValue = Numeric.toHexString(signedMessage);
```

### Expected behavior
It should return a SignatureData Object with the signature of the message using the credentials.

### Actual behavior
When the code arrives at `Sign.signMessage` it throws a `java.lang.RuntimeException: Could not construct a recoverable key. Are your credentials valid?` at Sign.java:115.

Here is the full error message:
```
java.lang.RuntimeException: Could not construct a recoverable key. Are your credentials valid?
    at org.web3j.crypto.Sign.createSignatureData(Sign.java:115)
    at org.web3j.crypto.Sign.signMessage(Sign.java:95)
```

## Environment
- Current web3j master branch, but I had it also happen with 4.8.8-android.
- Android and java version.
- Android 11 / LineageOS 19.1

**Comment by NickSneo** [comment] 2023-01-21 04:54
Hey @markusbug ,
In this 
`Sign.SignatureData signature = Sign.signMessage(messageBytes, credentials.getEcKeyPair(), false);`
The third parameter is boolean needToHash, we always hash the message string before signing it. 
So to sign long messages you will need to set the boolean needToHash=true, try again with this. Similar behaviour is with other web3 libraries too.
Since it is not a bug, will close this issue.

**Closed by NickSneo** 2023-01-21 04:54 UTC
Labels: bug
