### ISSUE TITLE
"Filter not found" detection could be improved

### ISSUE THREAD

**Issue by arobertn** [web3j/web3j#1839] opened 2022-12-27 13:54 UTC
If, for example, the web3 RPC node web3j is currently polling restarts, the filter can be lost. `Filter.java` tries to detect this condition by matching the RPC error code against -32000, which is "invalid input". However in practice various Ethereum node implementations are behaving differently here. E.g., Ganache is returning `-32700` (see log below). The current Ethereum JSON-RPC specification unfortunately simply doesn't specify which codes should be returned for different situations for each method and so implementers roll their own. In view of this, it might be better to detect "filter not found" by error message string comparison which, though imperfect, is likely to catch more cases with fewer false alarms than relying on `-32000`.

```
15:13:53.029 --> POST http://127.0.0.1:8545/
15:13:53.029 Content-Type: application/json; charset=utf-8
15:13:53.029 Content-Length: 74
15:13:53.029 
15:13:53.029 {"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x1"],"id":55}
15:13:53.029 --> END POST (74-byte body)
15:13:53.034 <-- 200 http://127.0.0.1:8545/ (4ms)
15:13:53.034 Content-Type: application/json
15:13:53.034 Content-Length: 1450
15:13:53.034 
15:13:53.034 {"id":55,"jsonrpc":"2.0","error":{"message":"filter not found","stack":"Error: filter not found\n    at EthereumApi.eth_getFilterChanges (.../ganache/dist/node/1.js:2:52758)","code":-32700}}
15:13:53.034 <-- END HTTP (1450-byte body)

15:13:53.034 WARN  o.w.p.c.filters.Filter   - Error sending request
org.web3j.protocol.core.filters.FilterException: Invalid request: filter not found
        at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:194)
        at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:144)
        at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mattiamonari** [comment] 2023-02-17 11:27
I don't know how the other clients implements the filter loss. Unless you can statistically prove that detecting the "filter not found" error message will result in less exception, I don't think it would make much sense to change it.
Probably, instead of changing the way of detecting the loss, it would be better to just add the Ganache case.

**Comment by gtebrean** [comment] 2023-03-01 17:14
As it is Ganache specific is not a bug related to web3j. Anyway I merged the PR above that should cover this

**Closed by gtebrean** 2023-03-01 17:14 UTC
Labels: bug
